profiling:
  models:
    - id: flat_svc_rbf
      path: ../../researches/research_202602_skuld_01_industrial_practice/predictors/flat_svc_rbf/model.pkl
      name: Универсальный оптимум
    - id: cascade_svc_poly_svc_rbf
      path: ../../researches/research_202602_skuld_01_industrial_practice/predictors/cascade_svc_poly_svc_rbf/model.pkl
      name: Корректор смещения
    - id: flat_svc_poly
      path: ../../researches/research_202602_skuld_01_industrial_practice/predictors/flat_svc_poly/model.pkl
      name: Справедливая модель